name: Release Please
env:
  RELEASE_PLEASE_DEBUG: "true"

on:
  push:
    branches:
      - main # Default branch
  pull_request:
    branches:
      - main # Optional, handle PRs to main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          token: ${{ secrets.GITHUB_TOKEN }}
          manifest-file: release-please-config.json
