name: Release Please

on:
  push:
    branches:
      - main # Adjust to your default branch

permissions:
  contents: write # Required to create releases
  pull-requests: write # Required to create pull requests

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Release Please
        uses: google-github-actions/release-please-action@v3 # Correct format
        with:
          release-type: node # Adjust for your project type
          token: ${{ secrets.GITHUB_TOKEN }}

