name: Release Please

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch (adjust if necessary)

permissions:
  contents: write # Needed to create release PRs
  pull-requests: write # Needed to create pull requests

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Run Release Please Action
      - name: Run Release Please
        uses: google-github-actions

